// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGjlnqujpc_b0-f0tBgQ8qX7vmZ_a5Duk',
    appId: '1:196536166335:web:c05f1cd3328d17d41a630a',
    messagingSenderId: '196536166335',
    projectId: 'move-on-87059',
    authDomain: 'move-on-87059.firebaseapp.com',
    storageBucket: 'move-on-87059.firebasestorage.app',
    measurementId: 'G-BQEDDGD80N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_akZTu5sjneUuM-wycZmPgBfXhZpwzM',
    appId: '1:196536166335:android:cd0c4210e7f8fe031a630a',
    messagingSenderId: '196536166335',
    projectId: 'move-on-87059',
    storageBucket: 'move-on-87059.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGH6-L6Z4yn5Xs1DwQ9c6908JxlPaEnnQ',
    appId: '1:196536166335:ios:49383fe8e236fc5b1a630a',
    messagingSenderId: '196536166335',
    projectId: 'move-on-87059',
    storageBucket: 'move-on-87059.firebasestorage.app',
    iosBundleId: 'com.example.moveonSample',
  );
}
